name: lyre
description: A flutter application for Reddit

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^2.0.0
  equatable: ^0.6.1
  shared_preferences: ^0.5.0
  clipboard_manager: ^0.0.4
  share: ^0.6.3+1
  auto_size_text: ^2.1.0
  material_design_icons_flutter: ^3.4.4595
  basic_utils: ^2.3.8
  flutter_markdown: ^0.3.2
  connectivity: ^0.4.6+1
  flutter_svg: ^0.15.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: '>=0.11.3+14'
  url_launcher: ^5.4.0
  rxdart: ^0.22.0
  draw: ^0.9.0
  swipedetector: ^1.2.0
  transparent_image: ^0.1.0
  flutter_cache_manager: ^0.3.0
  sqflite: ^1.1.0
  flutter_custom_tabs: ^0.6.0
  flutter_youtube: ^1.1.6
  uuid: ^2.0.0
  flutter_advanced_networkimage: ^0.6.2
  video_player: ^0.10.0
  path_provider: ^0.5.0+1
  image_picker: ^0.6.1
  flutter_widget_from_html_core: ^0.2.1+1
  retrofit: ^0.2.2
  flutter_inappbrowser: ^1.2.1
  flutter_html: ^0.11.0
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  screen: ^0.0.5
  photo_view: ^0.5.0  


dev_dependencies:
  hive_generator: ^0.7.0
  build_runner: ^1.7.1
  flutter_test:
    sdk: flutter
dependency_overrides:
  http: ^0.12.0
  path_provider: ^1.5.0
  url_launcher: ^4.0.0
  html: ^0.14.0+2
  rxdart: ^0.23.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
