name: lyre
description: A flutter application for Reddit

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: '>=0.11.3+14'
  url_launcher: ^5.0.1
  rxdart: ^0.18.0
  draw: ^0.5.0
  swipedetector: ^1.2.0
  html2md: ^0.3.0
  flutter_markdown: ^0.2.0
  transparent_image: ^0.1.0
  flutter_cache_manager: ^0.3.0
  sqflite: ^1.1.0
  photo_view: ^0.2.1
  flutter_custom_tabs: ^0.6.0
  flutter_youtube: ^1.1.6
  uuid: ^2.0.0
  flutter_advanced_networkimage:
    git:
      url: https://github.com/mchome/flutter_advanced_networkimage.git
      ref: 768895c2d4fabfaa357b2ae54871519270b877bb
  video_player: ^0.10.1+3
  path_provider: ^0.5.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  http: ^0.12.0
  path_provider: ^1.1.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
